import { RequestLog } from 'src/generated/graphql';

export type RequestLogPrint = [
  RequestLog['id'],
  RequestLog['method'],
  RequestLog['recordAt'],
  RequestLog['subject'],
  RequestLog['action'],
  RequestLog['route'],
  RequestLog['ip'],
  RequestLog['target'],
  RequestLog['adminId'],
  RequestLog['userId'],
  RequestLog['fingerprint'],
  RequestLog['companyId'],
  RequestLog['language'],
  RequestLog['query'],
  RequestLog['headers'],
  RequestLog['body'],
  RequestLog['params'],
  RequestLog['device'],
  RequestLog['location'],
  RequestLog['createdAt'],
  RequestLog['updatedAt'],
  RequestLog['beforeAt'],
  RequestLog['afterAt'],
  RequestLog['message'],
  RequestLog['duration'],
];

export const BuildRequestLogPrint = (log: RequestLog): RequestLogPrint => [
  log.id,
  log.method,
  log.recordAt,
  log.subject,
  log.action,
  log.route,
  log.ip,
  log.target,
  log.adminId,
  log.userId,
  log.fingerprint,
  log.companyId,
  log.language,
  log.query,
  log.headers,
  log.body,
  log.params,
  log.device,
  log.location,
  log.createdAt,
  log.updatedAt,
  log.beforeAt,
  log.afterAt,
  log.message,
  log.duration,
];
