onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - esbuild
  - prisma
  - prisma-zod-generator
  - unrs-resolver
