export const ModelsRelation = {
  Auth: {
    admin: 'Admin',
    member: 'Member',
    company: 'Company',
  },
  Admin: {
    role: 'AdminRole',
    companies: 'AdminCompany',
    auths: 'Auth',
    logs: 'RequestLog',
    mediaFolders: 'MediaFolder',
    mediaFiles: 'MediaFile',
    notifications: 'Notification',
    notificationRecipients: 'NotificationRecipient',
  },
  AdminRole: {
    admins: 'Admin',
  },
  AdminCompany: {
    admin: 'Admin',
    company: 'Company',
    role: 'CompanyRole',
  },
  Member: {
    companies: 'CompanyMember',
    auths: 'Auth',
    logs: 'RequestLog',
    mediaFolders: 'MediaFolder',
    mediaFiles: 'MediaFile',
    notifications: 'Notification',
    notificationRecipients: 'NotificationRecipient',
  },
  Company: {
    auths: 'Auth',
    admins: 'AdminCompany',
    roles: 'CompanyRole',
    members: 'CompanyMember',
    logs: 'RequestLog',
    mediaFolders: 'MediaFolder',
    mediaFiles: 'MediaFile',
    notifications: 'Notification',
    notificationRecipients: 'NotificationRecipient',
    websites: 'Website',
  },
  CompanyRole: {
    company: 'Company',
    members: 'CompanyMember',
    admins: 'AdminCompany',
  },
  CompanyMember: {
    company: 'Company',
    member: 'Member',
    role: 'CompanyRole',
  },
  Website: {
    company: 'Company',
  },
  Notification: {
    admin: 'Admin',
    member: 'Member',
    company: 'Company',
    recipients: 'NotificationRecipient',
  },
  NotificationRecipient: {
    admin: 'Admin',
    member: 'Member',
    company: 'Company',
    notification: 'Notification',
  },
  RequestLog: {
    member: 'Member',
    admin: 'Admin',
    company: 'Company',
  },
  MediaFolder: {
    parent: 'MediaFolder',
    children: 'MediaFolder',
    admin: 'Admin',
    member: 'Member',
    company: 'Company',
    files: 'MediaFile',
  },
  MediaFile: {
    folder: 'MediaFolder',
    admin: 'Admin',
    member: 'Member',
    company: 'Company',
  },
} as const;
